name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main
env:
  AZURE_APP_SERVICE_NAME: ${{ secrets.AZURE_APP_SERVICE_NAME }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_APP_SERVICE_NAME }}
  AZURE_PUBLISH_PROFILE_PATH: ${{ github.AZURE_PUBLISH_PROFILE_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: sudo apt install hugo
      
      - name: Build Hugo Site
        run: hugo --minify
        
      - name: Deploy Hugo Site to Azure App Service
        uses: azure/appservice-deploy@v1
        with:
          app-service-name: ${AZURE_APP_SERVICE_NAME}
          subscription-id:  ${AZURE_SUBSCRIPTION_ID}
          publish-profile-path:  ${AZURE_PUBLISH_PROFILE_PATH}
